import './AppLayout.css'
import { navigationForRoles } from '../auth/accessControl'
const initialsOf = (name) => name ? name.split(' ').filter(Boolean).slice(0, 2).map((p) => p[0].toUpperCase()).join('') : 'BW'
const BellIcon = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9" /><path d="M13.7 21a2 2 0 0 1-3.4 0" /></svg>
const PowerIcon = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M18.4 6.6a9 9 0 1 1-12.8 0" /><path d="M12 2v10" /></svg>
export default function AppLayout({ children, breadcrumb = 'Workspace / Overview', activeItem = 'Dashboard', onNavigate, user, onLogout }) {
  const displayName = user?.fullName || 'Jordan Doe'
  const displayRole = user?.roles?.[0] || 'Team member'
  const navigation = navigationForRoles(user?.roles ?? [])
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand__mark">BW</div><div><div className="brand__name">BuildSupply LK</div><div className="brand__tagline">Project operations</div></div></div><nav className="nav" aria-label="Main navigation"><div className="nav-label" aria-hidden="true">Workspace</div>{navigation.map((item) => <button key={item.path} type="button" className={`nav-item ${item.label === activeItem ? 'nav-item--active' : ''}`} onClick={() => onNavigate?.(item.path)}>{item.label}</button>)}</nav></aside><div className="app-main"><header className="topbar"><div><span className="mobile-brand">BuildWise</span><span className="breadcrumb">{breadcrumb}</span></div><div className="topbar__actions"><button className="icon-button" aria-label="Notifications"><BellIcon /></button><div className="user"><div className="avatar">{initialsOf(displayName)}</div><div className="user__meta"><div className="user__name">{displayName}</div><div className="user__role">{displayRole}</div></div></div>{onLogout && <button type="button" className="icon-button" aria-label="Sign out" title="Sign out" onClick={onLogout}><PowerIcon /></button>}</div></header><main className="content">{children}</main></div></div>
}
