// <auto-generated />
using System;
using BuildWise.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuildWise.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260924180819_CompleteQualityInspectionAndNcrWorkflow")]
    partial class CompleteQualityInspectionAndNcrWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildWise.Api.Models.Entities.AgentApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentWorkflowId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowId");

                    b.HasIndex("Decision");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("agent_approvals", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.AgentWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<string>("FinalOutcome")
                        .HasColumnType("text");

                    b.Property<int>("InitiatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaterialRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("MaterialRequestId");

                    b.HasIndex("Status");

                    b.ToTable("agent_workflows", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.AgentWorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AgentWorkflowId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StructuredResult")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationResult")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowId");

                    b.HasIndex("Status");

                    b.HasIndex("AgentWorkflowId", "StepOrder")
                        .IsUnique();

                    b.ToTable("agent_workflow_steps", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("MaterialRequestId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryReference");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("Status");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.DeliveryEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveryItemId")
                        .HasColumnType("integer");

                    b.Property<string>("FileType")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("DeliveryItemId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("DeliveryEvidences");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.DeliveryIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeliveryItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IssueType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReportedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("DeliveryItemId");

                    b.HasIndex("ReportedByUserId");

                    b.ToTable("DeliveryIssues");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.DeliveryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DamagedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("MaterialId");

                    b.ToTable("delivery_items", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.DeliverySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScheduledTimeSlot")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("DeliverySchedules");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InspectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("InspectionCriteria")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("InspectorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ObservedResult")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OverallDecision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("Status");

                    b.ToTable("inspections", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.InspectionEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("InspectionId")
                        .HasColumnType("integer");

                    b.Property<int?>("InspectionItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InspectionItemId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("InspectionId", "UploadedAt");

                    b.ToTable("inspection_evidences", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.InspectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcceptedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("InspectedQuantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("InspectionId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RejectedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.HasIndex("MaterialId");

                    b.ToTable("inspection_items", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.MaterialRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Normal");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateOnly>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RequiredDate")
                        .HasColumnType("date");

                    b.Property<int>("RevisionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("RevisionOfRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("SiteNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("RevisionOfRequestId");

                    b.HasIndex("Status");

                    b.ToTable("material_requests", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.MaterialRequestHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaterialRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("MaterialRequestId", "CreatedAt");

                    b.ToTable("material_request_history", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.MaterialRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("RequestedQuantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateOnly?>("RequiredDate")
                        .HasColumnType("date");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialRequestId", "MaterialId")
                        .IsUnique();

                    b.ToTable("material_request_items", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.NonConformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrectiveActionPlan")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("integer");

                    b.Property<int>("InspectionItemId")
                        .HasColumnType("integer");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("NcrNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("QuantityAffected")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("InspectionItemId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("NcrNumber")
                        .IsUnique();

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.ToTable("non_conformances", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ExpectedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuotationId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderDate");

                    b.HasIndex("ProjectId");

                    b.HasIndex("QuotationId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("OrderedQuantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuotationItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("QuotationItemId")
                        .IsUnique();

                    b.HasIndex("PurchaseOrderId", "QuotationItemId")
                        .IsUnique();

                    b.ToTable("purchase_order_items", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Quotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterialRequestId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("QuotationDate")
                        .HasColumnType("date");

                    b.Property<int?>("RfqId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MaterialRequestId");

                    b.HasIndex("RfqId");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.ToTable("quotations", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.QuotationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialRequestItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("QuotationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialRequestItemId");

                    b.HasIndex("QuotationId", "MaterialRequestItemId")
                        .IsUnique();

                    b.ToTable("quotation_items", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Rfq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IssuedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("RequiredResponseDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialRequestId");

                    b.HasIndex("Status");

                    b.ToTable("rfqs", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.RfqSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RfqId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("RfqId", "SupplierId")
                        .IsUnique();

                    b.ToTable("rfq_suppliers", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SiteEngineer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ProjectManager"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ProcurementOfficer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ProcurementManager"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ReceivingOfficer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "QualityInspector"
                        },
                        new
                        {
                            Id = 8,
                            Name = "SiteOfficer"
                        },
                        new
                        {
                            Id = 9,
                            Name = "SiteManager"
                        });
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.AgentApproval", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.AgentWorkflow", "AgentWorkflow")
                        .WithMany("Approvals")
                        .HasForeignKey("AgentWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.AgentWorkflow", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId");

                    b.HasOne("BuildWise.Api.Models.Entities.User", "InitiatedByUser")
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildWise.Api.Models.Entities.MaterialRequest", "MaterialRequest")
                        .WithMany("Workflows")
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Delivery");

                    b.Navigation("InitiatedByUser");

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.AgentWorkflowStep", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.AgentWorkflow", "AgentWorkflow")
                        .WithMany("Steps")
                        .HasForeignKey("AgentWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Approval", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.MaterialRequest", "MaterialRequest")
                        .WithMany("Approvals")
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Delivery", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Deliveries")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.DeliveryEvidence", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.DeliveryItem", "DeliveryItem")
                        .WithMany()
                        .HasForeignKey("DeliveryItemId");

                    b.HasOne("BuildWise.Api.Models.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId");

                    b.Navigation("Delivery");

                    b.Navigation("DeliveryItem");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.DeliveryIssue", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.DeliveryItem", "DeliveryItem")
                        .WithMany()
                        .HasForeignKey("DeliveryItemId");

                    b.HasOne("BuildWise.Api.Models.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId");

                    b.Navigation("Delivery");

                    b.Navigation("DeliveryItem");

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.DeliveryItem", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Delivery", "Delivery")
                        .WithMany("Items")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.DeliverySchedule", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Inspection", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.InspectionEvidence", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Inspection", "Inspection")
                        .WithMany("Evidence")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.InspectionItem", "InspectionItem")
                        .WithMany()
                        .HasForeignKey("InspectionItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BuildWise.Api.Models.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inspection");

                    b.Navigation("InspectionItem");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.InspectionItem", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Inspection", "Inspection")
                        .WithMany("Items")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inspection");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.MaterialRequest", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.MaterialRequest", "RevisionOfRequest")
                        .WithMany()
                        .HasForeignKey("RevisionOfRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");

                    b.Navigation("RequestedByUser");

                    b.Navigation("RevisionOfRequest");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.MaterialRequestHistory", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BuildWise.Api.Models.Entities.MaterialRequest", "MaterialRequest")
                        .WithMany("History")
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.MaterialRequestItem", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.MaterialRequest", "MaterialRequest")
                        .WithMany("Items")
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.NonConformance", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.InspectionItem", "InspectionItem")
                        .WithMany()
                        .HasForeignKey("InspectionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BuildWise.Api.Models.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InspectionItem");

                    b.Navigation("ResponsibleUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildWise.Api.Models.Entities.Quotation", "Quotation")
                        .WithOne("PurchaseOrder")
                        .HasForeignKey("BuildWise.Api.Models.Entities.PurchaseOrder", "QuotationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildWise.Api.Models.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");

                    b.Navigation("Quotation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildWise.Api.Models.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.QuotationItem", "QuotationItem")
                        .WithOne("PurchaseOrderItem")
                        .HasForeignKey("BuildWise.Api.Models.Entities.PurchaseOrderItem", "QuotationItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Material");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("QuotationItem");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Quotation", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.MaterialRequest", "MaterialRequest")
                        .WithMany("Quotations")
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.Rfq", "Rfq")
                        .WithMany()
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuildWise.Api.Models.Entities.Supplier", "Supplier")
                        .WithMany("Quotations")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialRequest");

                    b.Navigation("Rfq");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.QuotationItem", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.MaterialRequestItem", "MaterialRequestItem")
                        .WithMany("QuotationItems")
                        .HasForeignKey("MaterialRequestItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.Quotation", "Quotation")
                        .WithMany("Items")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialRequestItem");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Rfq", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.MaterialRequest", "MaterialRequest")
                        .WithMany("Rfqs")
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.RfqSupplier", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Rfq", "Rfq")
                        .WithMany("Suppliers")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rfq");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.UserRole", b =>
                {
                    b.HasOne("BuildWise.Api.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildWise.Api.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.AgentWorkflow", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Delivery", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Inspection", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.MaterialRequest", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("History");

                    b.Navigation("Items");

                    b.Navigation("Quotations");

                    b.Navigation("Rfqs");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.MaterialRequestItem", b =>
                {
                    b.Navigation("QuotationItems");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Quotation", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.QuotationItem", b =>
                {
                    b.Navigation("PurchaseOrderItem");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Rfq", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.Supplier", b =>
                {
                    b.Navigation("Quotations");
                });

            modelBuilder.Entity("BuildWise.Api.Models.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
